export default {
    API_GET_COURSE_BY_ID: 'API_GET_COURSE_BY_ID_COURSE_ROUTER',
    API_UPDATE_COURSE: 'API_UPDATE_COURSE_BY_ID_COURSE_ROUTER',
    API_UPDATE_COURSE_JSON_ONLY: 'API_UPDATE_COURSE_BY_ID_JSON_ONLY_COURSE_ROUTER',
    CLEAR_ERROR: 'CLEAR_ERROR_COURSE_ROUTER'
}