export default {
	EDIT_ENTRY_BASIC_DATA: 'EDIT_ENTRY_BASIC_DATA_ENTRY_EDITOR_EDIT_CONTENT',
	EDIT_ENTRY_CONTENT: 'EDIT_ENTRY_CONTENT_ENTRY_EDITOR_EDIT_CONTENT',
	COPY_DATA_FROM_SERVICES: 'COPY_DATA_FROM_SERVICES_ENTRY_EDITOR_EDIT_CONTENT',
	COPY_DATA_ERROR: 'COPY_DATA_ERROR_ENTRY_EDITOR_EDIT_CONTENT'
}