export default {
    API_GET_COURSE_BY_ID: 'API_GET_COURSE_BY_ID_EDIT_EXERCISES',
    UPDATE_EXERCISES: 'UPDATE_EXERCISES_EDIT_EXERCISES',
    EDIT_EXERCISE: 'EDIT_EXERCISE_EDIT_EXERCISES',
    ADD_EXERCISE: 'ADD_EXERCISE_EDIT_EXERCISES',
    API_UPDATE_EXERCISES: 'API_UPDATE_EXERCISES_EDIT_EXERCISES',
    PRE_DELETE_EXERCISE: 'PRE_DELETE_EXERCISE_EDIT_EXERCISES',
    DELETE_EXERCISE: 'DELETE_EXERCISE_EDIT_EXERCISES',
    RESTORE_DELETED_EXERCISE: 'RESTORE_DELETED_EXERCISE_EDIT_EXERCISES',
    CLEAR_MESSAGES: 'EDIT_EXERCISES_CLEAR_MESSAGES',
}