export default {
    INIT_TASKS_EDITOR: 'INIT_TASKS_EDITOR_EDIT_EXERCISE',
    ADD_NEW_TASK: 'ADD_NEW_TASK_EDIT_EXERCISE',
    EDIT_TASK: 'EDIT_TASK_EDIT_EXERCISE',
    UPDATE_TASKS: 'UPDATE_TASKS_EDIT_EXERCISE',
    TOGGLE_TASK_EXPAND: 'TOGGLE_TASK_EXPAND_EDIT_EXERCISE',
    CLEANUP: 'CLEANUP_EDIT_EXERCISE'
}