export default {
	API_GET_EXERCISE_BY_ID: 'API_GET_EXERCISE_BY_ID_EXERCISE_ROUTER',
	GET_STUDENT_ATTEMPTS: 'GET_STUDENT_ATTEMPTS_EXERCISE_ROUTER',
	API_NEW_ATTEMPT: 'API_NEW_ATTEMPT_EXERCISE_ROUTER',
	CLEANUP: 'CLEANUP_EXERCISE_ROUTER'
}