export default {
    INIT_TASKS_EDITOR: 'INIT_TASKS_EDITOR_EDIT_EXERCISE',
    ADD_ONE_CHOICE_TASK: 'ADD_ONE_CHOICE_TASK_EDIT_EXERCISE',
    ADD_MULTIPLE_CHOICE_TASK: 'ADD_MULTIPLE_CHOICE_TASK_EDIT_EXERCISE',
    ADD_TEXT_TASK: 'ADD_TEXT_TASK_EDIT_EXERCISE',
    EDIT_TASK: 'EDIT_TASK_EDIT_EXERCISE',
    UPDATE_TASKS: 'UPDATE_TASKS_EDIT_EXERCISE'
}