export default {
	API_GET_COURSE_BY_ID: 'API_GET_COURSE_BY_ID_MAIN',
	API_VIEW_COURSE: 'API_VIEW_COURSE_MAIN',
	CLEANUP: 'COURSE_ROUTER_MAIN_ROUTER_CLEANUP',
	GET_FIRST_TIME_STATUS: 'GET_FIRST_TIME_STATUS_MAIN_ROUTER'
}
