export default {
	GET_EXERCISE_FROM_COURSE: 'GET_EXERCISE_FROM_COURSE_EXERCISE_ROUTER',
	GET_STUDENT_ATTEMPTS: 'GET_STUDENT_ATTEMPTS_EXERCISE_ROUTER',
	API_NEW_ATTEMPT: 'API_NEW_ATTEMPT_EXERCISE_ROUTER',
	CLEANUP: 'CLEANUP_EXERCISE_ROUTER'
}