export default {
    API_GET_UPDATES_BY_DATE: 'API_GET_UPDATES_BY_DATE_DASHBOARD',
    CLEANUP: 'CLEANUP_DASHBOARD',
    UPDATE_STARTING_INDEX: 'UPDATE_STARTING_INDEX_DASHBOARD',
    UPDATE_FILTER: 'UPDATE_FILTER_DASHBOARD'
}