export default {
	API_CREATE_TOPIC: 'API_CREATE_TOPIC_COURSE_FORUM',
	GET_FORUM_FROM_COURSE: 'GET_FORUM_FROM_COURSE',
	CLEAR_FORUM_DATA: 'CLEAR_FORUM_DATA_FORUM',
	API_ANSWER_TOPIC_POST: 'API_ANSWER_TOPIC_POST_FORUM'
}