export default {
	API_GET_OPEN_COURSES: 'API_GET_OPEN_COURSES',
	API_GET_ENROLLED_COURSES: 'API_GET_ENROLLED_COURSES',
	API_GET_TEACHER_COURSES: 'API_GET_TEACHER_COURSES',
	API_GET_NOT_VIEWED_NOTIFICATIONS: 'API_GET_NOT_VIEWED_NOTIFICATIONS_COURSE_LIST',
	CLEAR_NOTIFICATIONS: 'CLEAR_NOTIFICATIONS_COURSE_LIST'
}