export default {
	API_GET_COURSE_BY_ID: 'API_GET_COURSE_BY_ID_MAIN',
	API_ENROLL_IN_COURSE: 'API_ENROLL_IN_COURSE',
	CLEAR_MESSAGES: 'ENROLLMENT_FORM_CLEAR_MESSAGES',
	API_DELETE_COURSE: 'API_DELETE_COURSE_MAIN'
}