export default {
	API_GET_COURSE_BY_ID: 'API_GET_COURSE_BY_ID_EDIT_COURSE',
	API_EDIT_COURSE: 'API_EDIT_COURSE',
	CLEAR_MESSAGES: 'EDIT_COURSE_CLEAR_MESSAGES',
	UPDATE_SECTIONS: 'EDIT_COURSE_UPDATE_SECTIONS',
	ADD_SECTION: 'ADD_SECTION_EDIT_COURSE',
	ADD_ENTRY: 'ADD_ENTRY_EDIT_CORUSE',
	EDIT_ENTRY: 'EDIT_ENTRY_EDIT_COURSE',
	DELETE_ENTRY: 'DELETE_ENTRY_EDIT_COURSE',
	EDIT_SECTION: 'EDIT_SECTION_EDIT_COURSE',
	DELETE_SECTION: 'DELETE_SECTION_EDIT_COURSE',
	API_GET_FILE_BY_ID: 'GET_FILE_BY_ID_EDIT_COURSE',
	PRE_DELETE_ENTRY: 'PRE_DELETE_ENTRY_EDIT_COURSE',
	PRE_DELETE_SECTION: 'PRE_DELETE_SECTION_EDIT_COURSE',
	RESTORE_DELETED_ENTRY: 'RESTORE_DELETED_ENTRY_EDIT_COURSE',
	RESTORE_DELETED_SECTION: 'RESTORE_DELETED_SECTION_EDIT_COURSE'
}