export default {
	API_GET_COURSE_BY_ID: 'API_GET_COURSE_BY_ID',
	GET_ENROLLMENT_STATUS: 'GET_ENROLLMENT_STATUS',
	API_ENROLL_IN_COURSE: 'API_ENROLL_IN_COURSE',
	CLEAR_MESSAGES: 'ENROLLMENT_FORM_CLEAR_MESSAGES'
}