export default {
	GET_ATTEMPT_BY_ID: 'GET_ATTEMPT_BY_ID_EXERCISE_ROUTER_ATTEMPT',
	TOGGLE_ATTEMPT_ANSWER: 'UPDATE_ATTEMPT_VALUE_EXERCISE_ROUTER_ATTEMPT',
	API_UPDATE_ATTEMPT: 'API_UPDATE_ATTEMPT_EXERCISE_ROUTER_ATTEMPT',
	API_FINISH_ATTEMPT: 'API_FINISH_ATTEMPT_EXERCISE_ROUTER_ATTEMPT',
	CLEANUP: 'CLEANUP_EXERCISE_ROUTER_ATTEMPT'
}