export default {
	API_ENROLL_IN_COURSE: 'API_ENROLL_IN_COURSE',
	CLEAR_MESSAGES: 'ENROLLMENT_FORM_CLEAR_MESSAGES',
	API_DELETE_COURSE: 'API_DELETE_COURSE_MAIN',
	API_ACCEPT_INVITE: 'API_ACCEPT_INVITE_COURSE_MAIN',
	API_SEND_TEACHER_INVITE: 'API_SEND_TEACHER_INVITE_COURSE_MAIN',
	API_SUBSCRIBE: 'API_SUBSCRIBE_COURSE_MAIN',
	API_UNSUBSCRIBE: 'API_UNSUBSCRIBE_COURSE_MAIN'
}