export default {
	API_GET_FORUM_BY_ID: 'API_GET_FORUM_BY_ID_FORUM',
	API_CREATE_TOPIC: 'API_CREATE_TOPIC_COURSE_FORUM',
	GET_FORUM_FROM_COURSE: 'GET_FORUM_FROM_COURSE',
	API_ANSWER_TOPIC_POST: 'API_ANSWER_TOPIC_POST_FORUM',
	API_DELETE_TOPIC_POST: 'API_DELETE_TOPIC_POST_FORUM',
	CLEANUP: 'FORUM_ROUTER_CLEANUP'
}